### ISSUE TITLE
where is byte pair encoding implemented in this project?

### ISSUE THREAD

**Issue by jeicy07** [ZhenYangIACAS/NMT_GAN#5]
Hi, I just split Chinese with jieba, but I don't know whether byte pair encoding is necessary in training. So could you release the bpe part of project, thanks!

**Comment by ZhenYangIACAS** [comment]
@jeicy07  We refer you to the paper (https://arxiv.org/pdf/1508.07909.pdf), where the detail about BPE has bee presented. Additionally, you can get the source code about the toolkit for implementing BPE. Since BPE can improve the translation performance significantly, we strongly suggest the utilization of BPE.

**Comment by jeicy07** [comment]
thanks a lot
